name: main
  
on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.13.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Install Dependencies
        run: yarn
      - name: Solidity Linter
        run: yarn solidity-linter
      - name: Solidity Tests
        run: npx hardhat test
      - name: Solidity Coverage
        run: NODE_OPTIONS=--max-old-space-size=4096 OVERRIDE_GAS_LIMIT=0xfffffffffff OVERRIDE_GAS_PRICE=1 npx hardhat coverage
